name: Varbase SEO - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - metatag
  - metatag_facebook
  - metatag_google_plus
  - metatag_hreflang
  - metatag_mobile
  - metatag_open_graph
  - metatag_twitter_cards
  - metatag_verification
  - pathauto
  - redirect
  - redirect_404
  - redirect_domain
  - schema_metatag
  - schema_article
  - schema_item_list
  - schema_web_page
  - schema_web_site
  - simple_sitemap
  - yoast_seo
  - script_manager
  - entity_clone
config:
  import:
    metatag_facebook: '*'
    metatag_google_plus: '*'
    metatag_hreflang: '*'
    metatag_mobile: '*'
    metatag_open_graph: '*'
    metatag_twitter_cards: '*'
    metatag_verification: '*'
    pathauto: '*'
    redirect: '*'
    redirect_404: '*'
    redirect_domain: '*'
    schema_metatag: '*'
    schema_article: '*'
    schema_item_list: '*'
    schema_web_page: '*'
    schema_web_site: '*'
    simple_sitemap: '*'
    yoast_seo: '*'
    script_manager: '*'
    entity_clone: '*'
    varbase_seo:
      - metatag.metatag_defaults.403
      - metatag.metatag_defaults.404
      - metatag.metatag_defaults.front
      - metatag.metatag_defaults.global
      - metatag.metatag_defaults.node
      - metatag.metatag_defaults.taxonomy_term
      - metatag.metatag_defaults.user
      - field.storage.node.field_meta_tags
      - field.storage.node.field_yoast_seo
  actions:
    pathauto.settings:
      simple_config_update: 
        enabled_entity_types:
          - user
        punctuation:
          hyphen: 1
        verbose: false
        separator: "-"
        max_length: 100
        max_component_length: 100
        transliterate: true
        reduce_ascii: false
        case: true
        ignore_words: "a, an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with"
        update_action: 2
        safe_tokens:
          - alias
          - path
          - join-path
          - login-url
          - url
          - url-brief
    redirect.settings:
      simple_config_update:
        canonical: false
        auto_redirect: true
        default_status_code: 301
        passthrough_querystring: true
        warning: false
        nonclean_to_clean: true
        ignore_admin_path: true
        frontpage_redirect: true
        deslash: true
        access_check: false
        normalize_aliases: true
        content_location_header: false
        term_path_handler: true
        route_normalizer_enabled: true
    simple_sitemap.settings:
      simple_config_update:
        max_links: 2000
        cron_generate: true
        cron_generate_interval: 0
        generate_duration: 10000
        remove_duplicates: true
        skip_untranslated: true
        batch_process_limit: 1500
        xsl: true
        base_url: ""
        default_variant: default
        custom_links_include_images: false
        excluded_languages: {}
        enabled_entity_types:
          - node
          - taxonomy_term
          - menu_link_content
    user.role.editor:
      grantPermissions:
        - 'use yoast seo'
    user.role.seo_admin:
      grantPermissions:
        - 'administer redirect settings'
        - 'administer redirects'
        - 'administer scripts'
        - 'administer meta tags'
        - 'use yoast seo'
        - 'administer sitemap settings'
        - 'clone script entity'
    user.role.content_admin:
      grantPermissions:
        - 'use yoast seo'
    user.role.site_admin:
      grantPermissions:
        - 'administer redirect settings'
        - 'administer redirects'
        - 'administer scripts'
        - 'administer meta tags'
        - 'use yoast seo'
        - 'administer sitemap settings'
        - 'clone script entity'
